### ISSUE TITLE
Adding a new item in wallet won't allow you to insert the first value

### ISSUE THREAD

**Issue by mattiapitossi** [mattiapitossi/expense-tracker#32]
Example: 
 You create a new wallet (e.g. ING bank)
 The value of the wallet is 0
 You have to insert all your income and expenses in order to set the correct value of the wallet

Be careful:
 When you add the possibility to insert the value of the wallet, this may already include some income/outcome on your expenses.   So, i'd be great to add the option to not insert the expense in the wallet.

**Comment by simo2898** [comment]
- [x] creating a wallet requires a value
- [x] value is 0 as default 
- [x] can insert a different value while creating a wallet 
- [x] can modify value after creating a wallet
- [ ] optional expense value checkbox
